/// Flutter icons MyFlutterApp
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';

  static const IconData cancel = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData help_circled = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData cog_outline = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData mail = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData logout = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData camera = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData clock = IconData(0xf017, fontFamily: _kFontFam);
  static const IconData chat_empty = IconData(0xf0e6, fontFamily: _kFontFam);
  static const IconData calc = IconData(0xf1ec, fontFamily: _kFontFam);
  static const IconData server = IconData(0xf233, fontFamily: _kFontFam);
}
